var palavras = [
    [['m','a','ç','ã'],['fruta']],
    [['c','o','l','h','e','r'],['talher']],
    [['p','r','o','v','a','s'],['escola']],
    [['t','ê','n','i','s'],['calçado']],
    [['g','a','t','o'],['animal']],
    [['m','o','s','q','u','i','t','o'],['inseto']],
    [['a','r','a','n','h','a'],['aracnídeo']],
    [['h','a','r','d','w','a','r','e'],['computador']],
    [['r','e','d','e'],['internet']],
    [['d','a','d','o','n','s'],['tecnologia']],
    [['Q','u','i','m','e','r','a'],['monstro']],
    [['E','m','p','a','t','i','a'],['habilidade']],
    [['o','l','h','o','s'],['corpo']],
    [['s','u','p','e','r','m','e','r','c','a','d','o'],['cidade']],
    [['a','l','e','x'],['nome']],
    [['m','a','n','h','ã'],['dia']],
    [['d','o','r','m','i','r'],['noite']],
    [['g','r','a','v','i','d','a','de'],['física']],
    [['e','n','e','r','g','i','a'],['calor']],
    [['ó','r','i','o','n'],['constelação']],
    [['r','i','t','u','a','l'],['magia']],
    [['y','u','g','i','o','h'],['jogo de cartas']],
    [['a','n','i','m','e','s'],['japão']],
    [['m','o','r','t','e'],['vida']],
    [['h','i','s','t','ó','r','i','a','s'],['lendas']],
];
